apiVersion: kubeflow.org/v1
kind: MPIJob
metadata:
  name: inc-distributed-tuning
spec:
  slotsPerWorker: 1
  runPolicy:
    cleanPodPolicy: Running
  mpiReplicaSpecs:
    Launcher:
      replicas: 1
      template:
        spec:
          containers:
          - image: thion2332/inc:v2
            name: mpi-launcher
            command:
            - mpirun
            args:
            - -np
            - "3"
            - --allow-run-as-root
            - -bind-to
            - none
            - -map-by
            - slot
            - -x
            - LD_LIBRARY_PATH
            - -x
            - PATH
            - -mca
            - pml
            - ob1
            - -mca
            - btl
            - ^openib
            - python
            - -u
            - /examples/pytorch/nlp/huggingface_models/text-classification/quantization/ptq_static/fx/run_glue.py  --model_name_or_path textattack/distilbert-base-uncased-MRPC --task_name mrpc --do_eval  --max_seq_length 128 --per_device_eval_batch_size 16 --no_cuda --output_dir ./int8_model_dir   --tune --overwrite_output_dir
            resources:
              limits:
                cpu: 1
    Worker:
      replicas: 3
      template:
        spec:
          containers:
          - image: thion2332/inc:v2
            name: mpi-worker
            resources:
              limits:
                cpu: 1